/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import DAO.ConexaoDAO;
import DAO.UsuarioDAO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import static javax.swing.UIManager.getString;

/**
 *
 * @author User
 */
public class frmPrincipalVIEW extends javax.swing.JFrame {
    
    Connection conn = null;
    PreparedStatement pstm = null;
    ResultSet rs = null;
    
    public frmPrincipalVIEW() {
        initComponents();

        //lblUsuarioPrincipal.setName(login.nome);
    }
    
    /*
    //--------------------------------------------------------------------------
    //Sistema de autenticidade
    
    public boolean autenticar (){

    String nome_usuario = lblUsuarioPrincipal.getText();
    String perfil = lblNivelPrincipal.getText();
    System.out.println(perfil);

        if (!perfil.equals("Admin")){
            return false;
            }
            return true;
    }
    
         public void teste(){
         
    frmCRUDClienteVIEW telaCRUDCliente = new frmCRUDClienteVIEW();
   
    String nome_usuario = lblUsuarioPrincipal.getText();
    String perfil = lblNivelPrincipal.getText();   

    //System.out.println(nome_usuario);    
    telaCRUDCliente.lblUsuarioCRUDCliente.setText(getString(nome_usuario));
    System.out.println(telaCRUDCliente.lblUsuarioCRUDCliente.getText());
    //telaCRUDCliente.lblNivelCRUDCliente.setText(rs.getString());
     }
    
    */
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bntAcessarCaixa = new javax.swing.JButton();
        bntCRUDCliente = new javax.swing.JButton();
        bntCRUDFuncionario = new javax.swing.JButton();
        bntCRUDProdutos = new javax.swing.JButton();
        bntSair = new javax.swing.JButton();
        lblBemVindo = new javax.swing.JLabel();
        lblFundo = new javax.swing.JLabel();
        lblUsuarioPrincipal = new javax.swing.JLabel();
        lblNivelPrincipal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bntAcessarCaixa.setContentAreaFilled(false);
        bntAcessarCaixa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bntAcessarCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAcessarCaixaActionPerformed(evt);
            }
        });
        getContentPane().add(bntAcessarCaixa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 260, 70));

        bntCRUDCliente.setContentAreaFilled(false);
        bntCRUDCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bntCRUDCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCRUDClienteActionPerformed(evt);
            }
        });
        getContentPane().add(bntCRUDCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 260, 70));

        bntCRUDFuncionario.setContentAreaFilled(false);
        bntCRUDFuncionario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bntCRUDFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCRUDFuncionarioActionPerformed(evt);
            }
        });
        getContentPane().add(bntCRUDFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 260, 70));

        bntCRUDProdutos.setContentAreaFilled(false);
        bntCRUDProdutos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bntCRUDProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCRUDProdutosActionPerformed(evt);
            }
        });
        getContentPane().add(bntCRUDProdutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 260, 70));

        bntSair.setContentAreaFilled(false);
        bntSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bntSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSairActionPerformed(evt);
            }
        });
        getContentPane().add(bntSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 190, 50));

        lblBemVindo.setFont(new java.awt.Font("Eras Medium ITC", 1, 24)); // NOI18N
        lblBemVindo.setForeground(new java.awt.Color(255, 255, 255));
        lblBemVindo.setText("Bem-Vindo");
        getContentPane().add(lblBemVindo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, -1, -1));

        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Tela Principal.jpg"))); // NOI18N
        lblFundo.setText("lbl");
        getContentPane().add(lblFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        lblUsuarioPrincipal.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        lblUsuarioPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuarioPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUsuarioPrincipal.setText("Usuario");
        lblUsuarioPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(lblUsuarioPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, -1, -1));

        lblNivelPrincipal.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        lblNivelPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        lblNivelPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNivelPrincipal.setText("Nivel");
        getContentPane().add(lblNivelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bntSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSairActionPerformed
    System.exit(0);
    }//GEN-LAST:event_bntSairActionPerformed

    private void bntAcessarCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAcessarCaixaActionPerformed
    frmCaixaVIEW acessarCaixa = new frmCaixaVIEW();
    acessarCaixa.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_bntAcessarCaixaActionPerformed

    private void bntCRUDClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCRUDClienteActionPerformed
        //teste();
        
        frmCRUDClienteVIEW telaCliente = new frmCRUDClienteVIEW();
        telaCliente.setVisible(true);
        this.dispose();  
    }//GEN-LAST:event_bntCRUDClienteActionPerformed

    private void bntCRUDFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCRUDFuncionarioActionPerformed
     frmCRUDFuncionarioVIEW telaFuncionario = new frmCRUDFuncionarioVIEW();
     telaFuncionario.setVisible(true);
     this.dispose();
        
     /*
    if (autenticar()){       
        frmCRUDFuncionarioVIEW telaFuncionario = new frmCRUDFuncionarioVIEW();
        telaFuncionario.setVisible(true);
        this.dispose();
        }
    else {
        JOptionPane.showMessageDialog(null, "Você não tem permissão para acessar esse campo.");
        }
    */
    }//GEN-LAST:event_bntCRUDFuncionarioActionPerformed

    private void bntCRUDProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCRUDProdutosActionPerformed
    frmCRUDProdutosVIEW telaProdutos = new frmCRUDProdutosVIEW();
    telaProdutos.setVisible(true);
    this.dispose();
        
    /*
    if (autenticar()){       
        frmCRUDProdutosVIEW telaProdutos = new frmCRUDProdutosVIEW();
        telaProdutos.setVisible(true);
        this.dispose();
        }
    else {
        JOptionPane.showMessageDialog(null, "Você não tem permissão para acessar esse campo.");
        }
    */
    }//GEN-LAST:event_bntCRUDProdutosActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
                //System.out.println(usuario.Codigo());
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipalVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntAcessarCaixa;
    private javax.swing.JButton bntCRUDCliente;
    private javax.swing.JButton bntCRUDFuncionario;
    private javax.swing.JButton bntCRUDProdutos;
    private javax.swing.JButton bntSair;
    private javax.swing.JLabel lblBemVindo;
    private javax.swing.JLabel lblFundo;
    public javax.swing.JLabel lblNivelPrincipal;
    public javax.swing.JLabel lblUsuarioPrincipal;
    // End of variables declaration//GEN-END:variables
}
